# Install act as a GitHub CLI extension to run locally
# https://github.com/nektos/act
# Then run "gh act"

name: integration

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: setup-folder
              uses: actions/checkout@v2
            
            - name: setup-dependencies
              run: |
                sudo apt update
                sudo apt install -y libgtest-dev lcov verilator gcc-riscv64-unknown-elf
            
            - name: run-tests
              run: |
                cd tb
                ./doit.sh
